version: '3'

services:
  flappy-bird:
    image: nginx:alpine
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST={$FLAPPY_BIRD_HOST}
      - NGINX_PORT=80
    volumes:
    - ./static:/usr/share/nginx/html